### PR TITLE
add colx

### PR DESCRIPTION
**Pull request by tinhnguyenhn**

### CODE REVIEW

**Comment by jowenshaw** [comment]
please pass the above checks of pull request.
run `make all` report `undefined: colxutil`

**Comment by tinhnguyenhn** [comment]
> 1. Please pass the following checks of pull request.
>    run `make all` report `undefined: colxutil`
> 2. Suggest rebase your commits on the latest anyswap:master branch
>    should update `tokens/colx/signtx.go` accordingly (ref. `tokens/btc/signtx.go`)

I updated. Thanks!

**Comment by jowenshaw** [comment]
> > 1. Please pass the following checks of pull request.
> >    run `make all` report `undefined: colxutil`
> > 2. Suggest rebase your commits on the latest anyswap:master branch
> >    should update `tokens/colx/signtx.go` accordingly (ref. `tokens/btc/signtx.go`)
> 
> I updated. Thanks!

still not solved problem 1. this problem is about repository `github.com/tinhnguyenhn/colxd`

the following is the concrete compiling error:
```
github.com/tinhnguyenhn/colxd/txscript
# github.com/tinhnguyenhn/colxd/txscript
/go/pkg/mod/github.com/tinhnguyenhn/colxd@v0.0.0-20210412084321-d9a38d090019/txscript/sign.go:74:14: undefined: godashutil
/go/pkg/mod/github.com/tinhnguyenhn/colxd@v0.0.0-20210412084321-d9a38d090019/txscript/sign.go:104:17: undefined: godashutil
/go/pkg/mod/github.com/tinhnguyenhn/colxd@v0.0.0-20210412084321-d9a38d090019/txscript/sign.go:168:50: undefined: godashutil
/go/pkg/mod/github.com/tinhnguyenhn/colxd@v0.0.0-20210412084321-d9a38d090019/txscript/sign.go:234:57: undefined: godashutil
/go/pkg/mod/github.com/tinhnguyenhn/colxd@v0.0.0-20210412084321-d9a38d090019/txscript/sign.go:346:9: undefined: godashutil
/go/pkg/mod/github.com/tinhnguyenhn/colxd@v0.0.0-20210412084321-d9a38d090019/txscript/sign.go:350:22: undefined: godashutil
/go/pkg/mod/github.com/tinhnguyenhn/colxd@v0.0.0-20210412084321-d9a38d090019/txscript/sign.go:353:37: undefined: godashutil
/go/pkg/mod/github.com/tinhnguyenhn/colxd@v0.0.0-20210412084321-d9a38d090019/txscript/sign.go:361:12: undefined: godashutil
/go/pkg/mod/github.com/tinhnguyenhn/colxd@v0.0.0-20210412084321-d9a38d090019/txscript/sign.go:365:25: undefined: godashutil
/go/pkg/mod/github.com/tinhnguyenhn/colxd@v0.0.0-20210412084321-d9a38d090019/txscript/sign.go:368:43: undefined: godashutil
/go/pkg/mod/github.com/tinhnguyenhn/colxd@v0.0.0-20210412084321-d9a38d090019/txscript/sign.go:368:43: too many errors
```

you can run `make all` in your forked repository `https://github.com/tinhnguyenhn/CrossChain-Bridge.git` to reproduce the above compile error.

Also you can see here `https://github.com/anyswap/CrossChain-Bridge/pull/13` if all checks are passed. For example, the current state is `All checks have failed`, means the pull request still have some problem.

**Comment by tinhnguyenhn** [comment]
> > > 1. Please pass the following checks of pull request.
> > >    run `make all` report `undefined: colxutil`
> > > 2. Suggest rebase your commits on the latest anyswap:master branch
> > >    should update `tokens/colx/signtx.go` accordingly (ref. `tokens/btc/signtx.go`)
> > 
> > 
> > I updated. Thanks!
> 
> still not solved problem 1. this problem is about repository `github.com/tinhnguyenhn/colxd`
> 
> the following is the concrete compiling error:
> 
> ```
> github.com/tinhnguyenhn/colxd/txscript
> # github.com/tinhnguyenhn/colxd/txscript
> /go/pkg/mod/github.com/tinhnguyenhn/colxd@v0.0.0-20210412084321-d9a38d090019/txscript/sign.go:74:14: undefined: godashutil
> /go/pkg/mod/github.com/tinhnguyenhn/colxd@v0.0.0-20210412084321-d9a38d090019/txscript/sign.go:104:17: undefined: godashutil
> /go/pkg/mod/github.com/tinhnguyenhn/colxd@v0.0.0-20210412084321-d9a38d090019/txscript/sign.go:168:50: undefined: godashutil
> /go/pkg/mod/github.com/tinhnguyenhn/colxd@v0.0.0-20210412084321-d9a38d090019/txscript/sign.go:234:57: undefined: godashutil
> /go/pkg/mod/github.com/tinhnguyenhn/colxd@v0.0.0-20210412084321-d9a38d090019/txscript/sign.go:346:9: undefined: godashutil
> /go/pkg/mod/github.com/tinhnguyenhn/colxd@v0.0.0-20210412084321-d9a38d090019/txscript/sign.go:350:22: undefined: godashutil
> /go/pkg/mod/github.com/tinhnguyenhn/colxd@v0.0.0-20210412084321-d9a38d090019/txscript/sign.go:353:37: undefined: godashutil
> /go/pkg/mod/github.com/tinhnguyenhn/colxd@v0.0.0-20210412084321-d9a38d090019/txscript/sign.go:361:12: undefined: godashutil
> /go/pkg/mod/github.com/tinhnguyenhn/colxd@v0.0.0-20210412084321-d9a38d090019/txscript/sign.go:365:25: undefined: godashutil
> /go/pkg/mod/github.com/tinhnguyenhn/colxd@v0.0.0-20210412084321-d9a38d090019/txscript/sign.go:368:43: undefined: godashutil
> /go/pkg/mod/github.com/tinhnguyenhn/colxd@v0.0.0-20210412084321-d9a38d090019/txscript/sign.go:368:43: too many errors
> ```
> 
> you can run `make all` in your forked repository `https://github.com/tinhnguyenhn/CrossChain-Bridge.git` to reproduce the above compile error.
> 
> Also you can see here `https://github.com/anyswap/CrossChain-Bridge/pull/13` if all checks are passed. For example, the current state is `All checks have failed`, means the pull request still have some problem.

thank you. I will check it again

**Comment by jowenshaw** [comment]
#15 pull request is merged which is same as this one.
So close this pull request.

**Pull request closed without merging**
